version: "3.1"

services:
  scheduler:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker_1:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-worker-1
    command: ["dask-worker", "tcp://scheduler:8786"]
    environment: 
      - EXTRA_CONDA_PACKAGES=wand==0.5.6
      - EXTRA_APT_PACKAGES=imagemagick wget
  
  worker_2:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-worker-2
    command: ["dask-worker", "tcp://scheduler:8786"]
    environment: 
      - EXTRA_CONDA_PACKAGES=wand==0.5.6
      - EXTRA_APT_PACKAGES=imagemagick wget

  notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    image: daskdev/dask-notebook
    hostname: notebook
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
      - EXTRA_CONDA_PACKAGES=wand==0.5.6
      - EXTRA_APT_PACKAGES=imagemagick
